### ISSUE TITLE
Node crashes when queried at inopportune times.

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-node#176]
**Bug Description**

When a node is queried for any data that requires the LMDB database access during finalization it will tend to crash with a corrupt database leaving only the option of deleting the database.

This happens because we are using the LMDB API somewhat incorrectly, namely http://www.lmdb.tech/doc/group__mdb.html#gaa2506ec8dab3d969b0e609cd82e619e5 `mdb_env_set_mapsize` requires that there are no outstanding database transactions when executed.

**Steps to Reproduce**

It is hard to reproduce deterministically without modifying the node, but it can be reliably reproduced by running queries `getBlocksAtHeight` + `getBlockInfo` + `getBlockSummary` in sequence by increasing block height while the node is catching up on the testnet. Likely just running `getBlocksAtHeight` would do the same.

This leads to a segmentation fault and analyzing the core dump leads to the following backtrace
```
[Current thread is 1 (Thread 0x7fb2a0b86700 (LWP 3313041))]
(gdb) backtrace
#0  0x00005644d2edd6fd in mdb_txn_renew0 ()
#1  0x00005644d2ede423 in mdb_txn_begin ()
#2  0x00007fb2a9a78d52 in ?? () at hsrc_lib/Database/LMDB/Raw.hsc:855
```

**Expected Result**

The node does not crash as a result of external queries.

**Actual Result**

The node crashes.

**Versions**
- Software Version: 1.1.2 (but I think any version starting with 1.0.0 is affected)

**Comment by abizjak** [comment]
We have discussed that the solution to go with to resolve the issue is to use a reader writer lock on the LMDB environment.

The writer lock should only be acquired when resizing the environment, and readers for normal operations.
